export const products = [
  {
    id: 1,
    title: "Sunburst",
    description: "Delivery within 3 hours",
    price: "2500",
    img: "https://assets.flowerstore.ph/public/tenantPH/app/assets/images/variant/400_ocnj1TpN6s9UzSRTDiUA8ZlD5.jpg",
    quantity: 1,
  },
  {
    id: 2,
    title: "Beautiful You",
    description: "Delivery within a day",
    price: "1399",
    img: "https://assets.flowerstore.ph/public/tenantPH/app/assets/images/variant/400_Q20yq8ilN6WqY7A8BYNVbXURq.webp",
    quantity: 1,
  },
  {
    id: 3,
    title: "Heather",
    description: "Delivery within 3 hours",
    price: "3500",
    img: "https://assets.flowerstore.ph/public/tenantPH/app/assets/images/product/350_NT3zeUWqI2By7VKIjwlb4y1L2.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "Bright red eternal love box",
    description: "Delivery within 2 hours",
    price: "90500",
    img: "https://assets.flowerstore.ph/public/tenantPH/app/assets/images/variant/400_PQialo6bbeMkOsoR7vPAhCLrq.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "Tickle me Pink",
    description: "Delivery within 5 hours",
    price: "2500",
    img: "https://assets.flowerstore.ph/public/tenantPH/app/assets/images/variant/400_oxUrVNdtwCFNYU3xyVARExPnE.jpg",
    quantity: 1,
  },
  {
    id: 6,
    title: "Heather",
    description: "Delivery within 2 hours",
    price: "3500",
    img: "https://assets.flowerstore.ph/public/tenantPH/app/assets/images/product/350_NT3zeUWqI2By7VKIjwlb4y1L2.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "Color of Love Bundle",
    description: "Delivery within 5 hours",
    price: "2500",
    img: "https://assets.flowerstore.ph/public/tenantPH/app/assets/images/variant/400_OK2pHBeXKq0swg2F1KrGv9QiC.webp",
    quantity: 1,
  },
  {
    id: 8,
    title: "Rose Diffuser",
    description: "Delivery within 1 hour",
    price: "90500",
    img: "https://assets.flowerstore.ph/public/tenantPH/app/assets/images/variant/400_mb4nBDtYRrjjQmv0UPYv2H8ex.jpg",
    quantity: 1,
  },
  {
    id: 9,
    title: "Pink Birthday in Can Bundle",
    description: "Delivery within 8 hours",
    price: "2500",
    img: "https://assets.flowerstore.ph/public/tenantPH/app/assets/images/variant/400_CHEVGB6yG5GU6kGlYx2OOkE9l.webp",
    quantity: 1,
  },
];
